spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://219.244.186.2:3306/qzkk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: snnucs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api