spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qzkk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Myself0514_ys
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api